### ISSUE TITLE
why you limit your clean and noise wav?

### ISSUE THREAD

**Issue by hongwen-sun** [anicolson/DeepXi#1]

**Comment by anicolson** [comment]
Can you please elaborate on that?

**Comment by hongwen-sun** [comment]
Sets used for training. For the validation set, identical filenames for the clean speech and noise must be placed in 'val_clean_speech' and 'val_noise', with the SNR at the end of the filename. As an example:
'./val_clean_speech/198_19-198-0003_Machinery17_15dB.wav' contains the clean speech, and './val_noise/198_19-198-0003_Machinery17_15dB.wav' contains the noise at the same length. They will be mixed together at the SNR level specified in the filename.

**Comment by hongwen-sun** [comment]
![image](https://user-images.githubusercontent.com/37586343/54892908-5f537a00-4eee-11e9-8de4-81151186ab14.png)

**Comment by hongwen-sun** [comment]
described in this file

**Comment by anicolson** [comment]
What is the issue, sorry?

**Comment by hongwen-sun** [comment]
I think it's better to combine the noise and clean voice in a cross-combine way.
I just don't understand why you limit the noise and clean voice in to a parallel format
![image](https://user-images.githubusercontent.com/37586343/54893804-801dce80-4ef2-11e9-92c8-15c1680a32ac.png)

**Comment by hongwen-sun** [comment]
besides, can you give me a link of dataset that you used in your paper?
your work is amazing

**Comment by anicolson** [comment]
From what I understand, you believe that it is better to have the noisy speech = clean speech + noise, pre-mixed beforehand? 

I want to do that, but the reason is that the target (a priori SNR) needs to be computed from the clean speech and noise spectrograms. If I pre-mix it, then I only have the noisy speech spectrogram available to me. There could possibly be a better way of doing this maybe. Does this make sense?

**Comment by anicolson** [comment]
Thank you, I will link it in the README.md very shortly

**Comment by hongwen-sun** [comment]
I think I have Misunderstand your describe in 
![image](https://user-images.githubusercontent.com/37586343/54893437-cd00a580-4ef0-11e9-8fd9-faba13d01904.png)
I realize you mean "identical filenames"  is just for the val data now.

**Comment by hongwen-sun** [comment]
thank you

**Comment by audier** [comment]
![image](https://user-images.githubusercontent.com/37586343/54893793-6bd9d180-4ef2-11e9-9895-8786cd7d3740.png)

**Comment by anicolson** [comment]
OK, I understand now. Cross-combine happens in training, while parallel combine occurs for validation.
