### ISSUE TITLE
What is the main difference between 3a version and 3d version?

### ISSUE THREAD

**Issue by NewEricWang** [anicolson/DeepXi#10]
Hi, anicolson:
     I have downloaded your 3d version to train enhance model. Based on my data, the ASR performance of 3d version is worse than that of 3a version on same epoch's model. I wondered that what is the main difference between 3a version and 3d version beside automatic computing of statistic information.

**Comment by anicolson** [comment]
there should be no other difference, i would be interested to know what performance difference you are getting?

I will have to look and find what is different

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anicolson** [comment]
Also, which gain function are you using? SRWF?

**Comment by anicolson** [comment]
There where minor changes, such as the periodic Hamming window was changed to tensorflows default periodic Hann window.

**Comment by NewEricWang** [comment]
Hi, anicolson :
     In my case, CWF is the best gain function.  The metric is WER.  
        -5db      0db     5db     10db    15db      20db 
3a    84.6       50.4    26.5     16.2     12.5       11.4
3d    85.3       51.0    26.6     16.6     12.6       11.8
        The above performance is obtained at 250th epoch.

**Comment by anicolson** [comment]
OK, ill get back to you about this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
