### ISSUE TITLE
‘train_s_list’ not found.

### ISSUE THREAD

**Issue by fangxiao-dev** [anicolson/DeepXi#13]
```
Finding sample statistics...
Traceback (most recent call last):
  File "deepxi.py", line 244, in <module>
    args = get_stats(args, config)
  File "deepxi.py", line 95, in get_stats
    random.shuffle(args.train_s_list) # shuffle list.
AttributeError: 'Namespace' object has no attribute 'train_s_list'
```
Could you help me with this? Thanks.

**Comment by anicolson** [comment]
Hi, can you show me how you are calling the deepxi.py script?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fangxiao-dev** [comment]
sorry to bother, I shouldn't rush, I guess that's because I didn't add any test/train/val wave file. But an additional advice: the 24-bit wav file would also cause error.
