### ISSUE TITLE
get an erorr when run python3 deepxi.py --infer 1 --out_type y --gain mmse-lsa --gpu 0

### ISSUE THREAD

**Issue by xiaoyaoxiaoxian** [anicolson/DeepXi#14]
Hi anicolson,
    It seems the latest version has problem when only run 'python3 deepxi.py --infer 1 --out_type y --gain mmse-lsa --gpu 0'  command.
   train_s_list can not be found . It seems I must run run.sh script. Is it possible only performance Inference? 

  File "deepxi.py", line 254, in <module>
    args = get_stats(args, config)
  File "deepxi.py", line 95, in get_stats
    random.shuffle(args.train_s_list) # shuffle list.
AttributeError: 'Namespace' object has no attribute 'train_s_list'

**Comment by anicolson** [comment]
Hi, can you try with the updated args.py module? The “ver” argument was set to “3d” instead of “3e”

**Comment by xiaoyaoxiaoxian** [comment]
It seems I need to add some args. I run following command and a get a result in out dir
python3 deepxi.py --infer 1 --ver '3e' --set_path='set' --data_path='data' --out_type y --gain mmse-lsa --gpu 0

**Comment by xiaoyaoxiaoxian** [comment]
Thanks anicolson. It seems the args not set issue. After update the code,  It can run OK. I think previously it was args issue just as you said.
