### ISSUE TITLE
Is ResNet 3f causal？

### ISSUE THREAD

**Issue by cohendrake** [anicolson/DeepXi#18]
Good job. As layer normalization is widely used in the ResNet 3f, I doubt that it's a causal network—‘future’  features are actually included. I've tried to remove all the layer normalizations and the results turn out to be much worse.
Is layer normalization dispensable?

**Comment by anicolson** [comment]
Hi,

The layer normalisation typically employed in networks is sequence-wise layer normalisation. The statistics are thus calculated over all the features of a frame and over the entire sequence. So you are right, layer normalisation is non-causal.

However, 3f is using frame-wise layer normalisation. The statistics are calculated only over the features of the frame for frame-wise layer normalisation. This means that no features from future frames are used for the current frame, giving us a causal form of layer normalisation.

Hope this helps.
________________________________

**Comment by cohendrake** [comment]
Thanks!  Do you mean this causal form of layer normalization is applied over different dimensions of the feature for the current frame?

**Comment by cohendrake** [comment]
Thanks!  Do you mean this causal form of layer normalization is applied over different dimensions of the feature for the current frame?

**Comment by anicolson** [comment]
So the statistics are calculated over all of the dimensions of the current frame. e.g. over the 257 frequency bins of the current frame, giving a mean and variance both of size 1. Each of the frequency bins is then normalised using the same mean and variance.

Hope this helps

**Comment by cohendrake** [comment]
Got it.
