### ISSUE TITLE
ValueError: Sample larger than population

### ISSUE THREAD

**Issue by xiaojian10** [anicolson/DeepXi#2]
I enter the command: python3 deepxi.py --train 1 --verbose 1 --gpu 0 . and There was an error and don't know how to solve it .
bus id: 0000:01:00.0, compute capability: 6.1)
Creating epoch parameters, as no pickle file exists...
Traceback (most recent call last):
  File "deepxi.py", line 263, in <module>
    mbatch_size_iter, train_clean_speech_mbatch_seq_len) # generate mini-batch of noise training waveforms.
  File "../../../../lib\batch.py", line 53, in _noise_mbatch
    mbatch_list = random.sample(noise_list, mbatch_size) # get mini-batch list from training list.
  File "C:\Program Files\Anaconda3\lib\random.py", line 315, in sample
    raise ValueError("Sample larger than population")
ValueError: Sample larger than population

**Comment by xiaojian10** [comment]
![image](https://user-images.githubusercontent.com/43231974/59825644-28fb8e80-9367-11e9-8d9f-560ede17757b.png)

**Comment by xiaojian10** [comment]
![image](https://user-images.githubusercontent.com/43231974/59825668-3ca6f500-9367-11e9-8989-7d4d829218c2.png)

**Comment by anicolson** [comment]
Hi, you only have 5 noise files and a mini-batch size of 10. You can either reduce your mini-batch size (e.g. args.mbatch_size = 5) or add more noise sources. If you add more noise sources, make sure to delete the noise list pickle file in the data directory (otherwise it won't update).
