### ISSUE TITLE
Add noise creates nan values

### ISSUE THREAD

**Issue by djo-koconi** [anicolson/DeepXi#26]
Hi Aaron.

I'm experimenting with training. 
Just mbatch[0] is getting filled with many **nan** and zero values after mixing the clean and noisy samples.

Disabling addition of noise clears mbatch[0] from **nan** values.

Is there some specific rule to follow when adding clean and noisy data? 
I'm experimenting with small section of Librispeech and Environmental Background Noise dataset so the file lengths should be ok.

**Comment by anicolson** [comment]
in line 76 of add_noise.py, are you able to check if ``tf.norm(d)`` produces zeroes at any time?

**Comment by djo-koconi** [comment]
Seems that `tf.norm` does create zeros, so we get division by 0 which creates **nan** values.
I eliminated `tf.norm` from the code and no more nan values:

`d = tf.multiply(d, tf.truediv(s, tf.pow(10.0, tf.multiply(0.05, SNR))))`


Any suggestion about the issue?

What is the intention behind normalizing the values in this case?

**Comment by anicolson** [comment]
I will have to find a source/reference for this. I believe there might be a reference in "Speech Enhancement: Theory and Practice" by Loizou if someone can check.

**Comment by anicolson** [comment]
Please see line 232 of:  https://github.com/anicolson/DeepXi/blob/tf2/deepxi/sig.py for a potential fix.

**Comment by djo-koconi** [comment]
Thank you.

I had a look at tf2 version. Looking forward to the release :)
