### ISSUE TITLE
Can you share the ResLSTM codes?

### ISSUE THREAD

**Issue by 20050710212** [anicolson/DeepXi#27]
Thank you for such a fantastic work. 

I am also interested in the ResLSTM and want to train it myself. Could you share the codes with me?  I' d appreciate any help. By the way, what is the RDLNet? Is it a great progress in WER? When will it be released? 

Thank you!

**Comment by anicolson** [comment]
ResLSTM has been added. I have not tested it with the current code, so please let me know of any issues.

RDLNet can be found here: https://arxiv.org/abs/2002.12794. This will be made available within the next couple of weeks hopefully. I will post some speech enhancement results for it as well to compare it to ResNet.

**Comment by 20050710212** [comment]
Thanks for the codes and the paper and I will read them soon. Furthermore, I am looking forward to your new work.

**Comment by 20050710212** [comment]
@anicolson 
Hi Aaron, I find that the training process of ResLSTM seems very very slow, compared to ResNet. For example, it takes about 20 s/iter for ResLSTM, but  4 iter/s for ResNet.

**Comment by anicolson** [comment]
This is why I switched to ResNet. Training an LSTM architecture is very time-consuming.

**Comment by 20050710212** [comment]
Thank you. 
I use a RTX2080. Is it reasonable that the train speed of ResNet is 80 times faster than that of ResLSTM?

**Comment by anicolson** [comment]
Yes

**Comment by 20050710212** [comment]
Thanks a lot.

**Comment by 20050710212** [comment]
@anicolson 
Hi, Aaron, thanks for the sharing of the RDLnet peper. 
In the experiment section, the configuration of the ResNet is different from the DeepXi. It says,
> Each residual block contained 2 causal dilated convolutional units with an output size of 64, and a kernel size of 3. For each block, d was cycled from 1 to 8 (increasing by a power of 2). ResNets of sizes 0.53, 1.03, 1.53, and 2.03 million parameters were formed by cascading 20, 40, 60, and 80 residual locks, respectively.

1. Is it more efficient by using this structure as described in the paper?
2. Is the structure I drawed right? Thank you so much.
![image](https://user-images.githubusercontent.com/4574648/80346319-24fc9f00-889d-11ea-8fb9-7ad46c785cc9.png)

**Comment by anicolson** [comment]
Please see this for the resnet: https://ieeexplore.ieee.org/document/9066933

It utilises bottleneck residual blocks, which are more parameter efficient than normal blocks (from RDLNet paper).  It is the same one available on the deep xi repository.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 20050710212** [comment]
Thank you so much.
