### ISSUE TITLE
Cannot feed value of shape (1, 9582560, 2) for Tensor 's_ph:0', which has shape '(?, ?)'

### ISSUE THREAD

**Issue by darkdante2209** [anicolson/DeepXi#29]
I'm trying to test denoise with my file, after put my .wav file to test folder and run inference command, i got these errors, how could I fix it? thank you.
`  File "deepxi.py", line 44, in <module>
    if args.infer: infer(sess, net, args)
  File "lib/dev/infer.py", line 34, in infer
    input_feat = sess.run(net.infer_feat, feed_dict={net.s_ph: [wav], net.s_len_ph: [j['seq_len']]}) # sample of training set.
  File "/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 9582560, 2) for Tensor 's_ph:0', which has shape '(?, ?)'
`

**Comment by anicolson** [comment]
You are trying to feed stereo (two-channel) audio into Deep Xi. Deep Xi in its current configuration is only designed for mono (single-channel) audio.

Hope this helps.

**Comment by darkdante2209** [comment]
Thanks alot, it was really stereo, i used audacity to convert it to mono.
