### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'mu'

### ISSUE THREAD

**Issue by abramovi** [anicolson/DeepXi#3]
Hi ,

I am trying to run Inference by - `python3 deepxi.py --infer 1 --out_type y --gain mmse-lsa --gpu 0
`
But I am getting the follwing - 

> Traceback (most recent call last):
  File "deepxi.py", line 284, in <module>
    net = deepxi_net(args)
  File "deepxi.py", line 87, in __init__
    args.fs, self.P, args.nconst, args.mu, args.sigma) # feature graph.
AttributeError: 'Namespace' object has no attribute 'mu'

it happen also when I provide stats_path

**Comment by longjewel** [comment]
> Hi ,
> 
> I am trying to run Inference by - `python3 deepxi.py --infer 1 --out_type y --gain mmse-lsa --gpu 0 `
> But I am getting the follwing -
> 
> > Traceback (most recent call last):
> > File "deepxi.py", line 284, in 
> > net = deepxi_net(args)
> > File "deepxi.py", line 87, in **init**
> > args.fs, self.P, args.nconst, args.mu, args.sigma) # feature graph.
> > AttributeError: 'Namespace' object has no attribute 'mu'
> 
> it happen also when I provide stats_path

I had the same problem. Did you solve the problem?

**Comment by abramovi** [comment]
No ..

**Comment by anicolson** [comment]
Sorry guys, it should be self.mu, and self.sigma, not args.mu, and args.sigma in line 87. I have corrected this in the code.

Please tell me if this fixes the problem.
