### ISSUE TITLE
Multi gpu trainin

### ISSUE THREAD

**Issue by djo-koconi** [anicolson/DeepXi#32]
Hello. Its great to see Deep Xi in tfv2 :)

Is multi gpu training supported in utils/gpu_config? Can we pass more than 1 gpu value as run.sh argument?
I am trying to implement Distributed training with Keras, just it seems to have a conflict with gpu finding process in run.sh.

**Comment by anicolson** [comment]
Hi, yes, tf2 is much better 👍.

Try, using GPU “0,1” with the arguments of run.sh if you want to use your first 2 gpus for example. I will have to verify this when i get time. Please message me the result.
 Hope this helps.

**Comment by djo-koconi** [comment]
Thanks, Ill give it a go and let you know.

By the way, did you try larger batch sizes? 
16 can also run with 1 gpu (12GB).

**Comment by anicolson** [comment]
I have not tried it. I would be interested to know how big the difference is.

**Comment by djo-koconi** [comment]
Multi GPU training doesn't work as it is. Keras distributed training should be not so tricky to implement. I will give it a try.
Also, I ran a small training with mbatch size =12 and it doesn't seem to degrade the training process.
