### ISSUE TITLE
How to run version resnet-1.0n?

### ISSUE THREAD

**Issue by darkdante2209** [anicolson/DeepXi#35]
I try to run the command with version resnet-1.0n but it responsed this: 
`ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on model/resnet-1.0n/epoch-179/variables/variables: Not found: model/resnet-1.0n/epoch-179/variables; No such file or directoryValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on model/resnet-1.0n/epoch-179/variables/variables: Not found: model/resnet-1.0n/epoch-179/variables; No such file or directory`

**Comment by anicolson** [comment]
That is because a trained model is only available for resnet-1.0c at the moment, not resnet-1.0n

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
