### ISSUE TITLE
Errors during training

### ISSUE THREAD

**Issue by xiaojian10** [anicolson/DeepXi#36]
When I put 100 noise voices in the training noise folder, run python deepxi.py --train 1 --ver 'ANY_NAME' --gpu 0, the code will run normally. But when I put 2000 noise speech in the training noise folder, the code will report an error when the second epoch ends. The error is as follows:

![wrong](https://user-images.githubusercontent.com/43231974/81198756-5f5af000-8fb1-11ea-8f1a-577fb5d8c955.png)

**Comment by xiaojian10** [comment]
I do n’t know what caused this, and I hope you can give me some suggestions in your free time.

**Comment by anicolson** [comment]
Hi, can you please update Deep Xi. This is the old version using Tensorflow 1. Deep Xi has been overhauled since this version, and now uses Tensorflow 2.

Hopefully this resolves your problems.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
