### ISSUE TITLE
Clarity on file format reqruired in '/set' folder

### ISSUE THREAD

**Issue by archiki** [anicolson/DeepXi#38]
Hi @anicolson ,
Can you elaborate which folders are to be present in the set folder and what files they should contain along with the naming restrictions. It is not very clear in your readme files.
Thanks in advance!

**Comment by anicolson** [comment]
Thank you for your comment.

Please see the updated README.md for a clear explanation of the naming conventions in `set`.

If this is not clear, please let me know.

Hope this helps,
Aaron.
