### ISSUE TITLE
How to get my own mu.mat？

### ISSUE THREAD

**Issue by NewEricWang** [anicolson/DeepXi#4]
Hi, @anicolson , 
     Thanks for your great work! 
     I want to train DeepXi model using my own data now. But I don't know how to get mu.mat and sigma.mat based on my data. Could you give me some help? 
     Any advices will be appreciated!

**Comment by anicolson** [comment]
Hi, thank you, mu.mat contains a vector of size NFFT/2 + 1 (257). xi_dB(n,k)=10*log10(xi(n,k)), where n is frame index and k is frequency index from k=0 to k=NFFT/2+1.

The mean for each frequency component is taken over the training set, i.e. for the k^th component, mean(xi_dB(:,k)). Similarly for the standard deviation: stddev(xi_dB(:,k))

once you compute this vector, it can replace mu.mat, just store in in a numpy array or a pickle file.

more details can be found in the manuscript.

https://maxwell.ict.griffith.edu.au/spl/publications/papers/spcom19_aaron_deep.pdf

hope this helps

please contact me again if this is not clear

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NewEricWang** [comment]
@anicolson, thank you again!
