### ISSUE TITLE
Denoise Live Microphone Feed

### ISSUE THREAD

**Issue by vinod1234567890** [anicolson/DeepXi#42]
Hi,

Thank you for open sourcing such awesome work.

i'm trying to deploy your model for live de-noising of microphone input:
using the default parameters and the pretrained resnet-1c model.
But the output is cancelling out the speech and adding loud artefacts.

please suggest if this model can be used at all for live processing. if yes, what do i need to do in terms of pre/post-processing

**Comment by anicolson** [comment]
Hi, 

Sorry I have been a bit busy lately.

I would be interested in developing this for Deep Xi.

It should be able to. A buffer would be needed, as the current network can utilise 8 seconds of audio.

There would be the overhead of doing analysis and synthesis.

Please contact me if you are interested in this.

Regards,
Aaron.
