### ISSUE TITLE
I can't find the implementation of addnoise function from deep_xi_test_set.m

### ISSUE THREAD

**Issue by ahikaml** [anicolson/DeepXi#43]
Is it placed in other module? Can you help me please to find it? 
Thanks

**Comment by yunzqq** [comment]
Please find the deepxi/sig.py file





------------------ Original ------------------

**Comment by ahikaml** [comment]
Hi,
The function 'add_noise' in sig.py is in python while I searched for the matlab function addnoise for: [x.wav, ~] = addnoise(s.wav(:), d.wav(:), q); % noisy speech.  
I understand that the functionality is supposed to be similar but I thought that this function is implemented somewhere (otherwise we get an error..)

**Comment by anicolson** [comment]
Hi, please use the following:

https://github.com/anicolson/matlab_feat/blob/master/feat/add_noise.m

**Comment by ahikaml** [comment]
Thanks!
