### ISSUE TITLE
i can not find the freesound packs. does it mean Sound Ids 

### ISSUE THREAD

**Issue by xxk101010** [anicolson/DeepXi#46]
i can not find the freesound packs. does it mean Sound Ids.
![feesound](https://user-images.githubusercontent.com/35319060/89103628-b869e100-d445-11ea-8094-042f2500011d.png)

**Comment by anicolson** [comment]
Hi,

It is a bit odd as you used to be able to search by the pack number. Once the pack has been downloaded, the pack number is shown at the start of each pack .zip file as follows:
![image](https://user-images.githubusercontent.com/26111230/89134579-881b6300-d569-11ea-8a1f-7c62f0fecc2d.png)

![image](https://user-images.githubusercontent.com/26111230/89134592-949fbb80-d569-11ea-9201-c67ab2e5780b.png)

These packs are included in the Deep Xi Training Set: [https://ieee-dataport.org/open-access/deep-xi-training-set](https://ieee-dataport.org/open-access/deep-xi-training-set)

**Comment by xxk101010** [comment]
it works for me. thanks a lot
