### ISSUE TITLE
How to decrease the distortion of enhanced speech?

### ISSUE THREAD

**Issue by NewEricWang** [anicolson/DeepXi#6]
Hi, anicolson
      I got my own enhanced speech by using your project. I can observe the improvement of the enhance speech. Now I want to use the enhanced speech to perform ASR. But I find the performance of enhanced speech is not better than that of noisy speech. How should I adjust the parameters or change the code to decrease the distortion of the enhanced speech?  Could you give some directions about it?
Thank you very much!

**Comment by anicolson** [comment]
See this paper: https://arxiv.org/pdf/1906.07319.pdf

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NewEricWang** [comment]
Great! Thank you!
