### ISSUE TITLE
what about the speech enhancement performance between DeepXi-ResBLSTM and DeepXi-TCN?

### ISSUE THREAD

**Issue by melspectrum007** [anicolson/DeepXi#7]
As you mentioned in "README"
The ResLSTM and ResBLSTM networks used for Deep Xi in [1] (Deep Xi - ResLSTM and Deep Xi - ResBSLTM) have been replaced with a residual network (ResNet) that employs TCN.

becuase there isn't any description about DeepXi-TCN in the paper "Deep learning for minimum mean-square error approaches to speech enhancement, Speech", so what about the speech enhancement performance between DeepXi-ResBLSTM and DeepXi-TCN? 

Thanks

**Comment by anicolson** [comment]
[ResNet.txt](https://github.com/anicolson/DeepXi/files/3450162/ResNet.txt)
[ResBSLTM.txt](https://github.com/anicolson/DeepXi/files/3450167/ResBSLTM.txt)
[ResLSTM.txt](https://github.com/anicolson/DeepXi/files/3450168/ResLSTM.txt)

Here are objective scores of each
