### ISSUE TITLE
Do i need to create my own mu.mat?

### ISSUE THREAD

**Issue by rishabh-ojha98** [anicolson/DeepXi#9]
I am using my own clean speech data and noises. Do i have to create new **mu.mat** & **sigma.mat** or not?

**Comment by anicolson** [comment]
not necessarily. are u using your own training set? it might only significantly affect performance if you use a different range of snr levels for training. I think those stats were calculated for snr levels ranging from -10 to 20 dB

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anicolson** [comment]
I am planning to update the code within the next few weeks so that the stats are computed automatically in the script anyway.

**Comment by rishabh-ojha98** [comment]
The SNR range is 0 to 20 dB for my training set.

**Comment by anicolson** [comment]
it should be fine then. You can always see if there is an improvement after I update (which will be soon)
